--
-- PostgreSQL database dump
--

\restrict FSrh1Xm04TDalytaJLEZ8CoeLnWofr5Pw0y7YTVBRfDZZzzK9idtaTbsUnEKHqL

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg13+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    account_number character varying(255) NOT NULL,
    account_type character varying(255) NOT NULL,
    balance numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    customer_id bigint NOT NULL
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: beneficiaries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.beneficiaries (
    id bigint NOT NULL,
    account_number character varying(255) NOT NULL,
    bank_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    ifsc_code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    customer_id bigint NOT NULL
);


ALTER TABLE public.beneficiaries OWNER TO postgres;

--
-- Name: beneficiaries_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.beneficiaries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.beneficiaries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consents (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    data_access character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone,
    purpose character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    customer_id bigint NOT NULL,
    created_by character varying(255),
    approved_at timestamp(6) without time zone,
    approved_by character varying(255),
    rejected_at timestamp(6) without time zone,
    rejected_by character varying(255)
);


ALTER TABLE public.consents OWNER TO postgres;

--
-- Name: consents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    username character varying(255),
    password character varying(255)
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    balance_after numeric(15,2) NOT NULL,
    description character varying(255),
    transaction_date timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    account_id bigint NOT NULL
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts (id, account_number, account_type, balance, created_at, status, customer_id) FROM stdin;
2	ACC10003	CURRENT	0.00	2026-09-28 22:47:35.928263	CLOSED	3
1	ACC10002	SAVINGS	14500.00	2026-09-28 22:47:17.168057	ACTIVE	2
35	ACC10009	SAVINGS	0.00	2026-10-04 20:56:15.353254	ACTIVE	8
36	100299865382	SAVINGS	0.00	2026-10-05 15:06:27.726895	ACTIVE	8
37	100542873500	CURRENT	0.00	2026-10-05 19:31:54.033061	ACTIVE	5
3	ACC10022	SAVINGS	8000.00	2026-09-28 22:50:33.776094	ACTIVE	2
34	ACC10008	SAVINGS	0.00	2026-10-04 19:39:49.36657	CLOSED	8
\.


--
-- Data for Name: beneficiaries; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.beneficiaries (id, account_number, bank_name, created_at, ifsc_code, name, status, customer_id) FROM stdin;
1	BE0001	ABC Bank	2026-09-29 16:02:42.356547	ABCD0001234	Arun Kumar	ACTIVE	2
2	BE0002	UCO Bank	2026-09-29 16:03:52.445098	UCOD0001234	Sathana	ACTIVE	6
3	BE0002	UCO Bank	2026-09-29 16:05:16.134048	UCOD0001234	Sathana	ACTIVE	5
4	BE0003	UCO Bank	2026-09-29 16:06:08.384497	UCOD001234	Sahaya M	INACTIVE	5
34	123456789012	State Bank of India	2026-10-03 15:16:46.925529	SBIN0001234	Arun Kumar	ACTIVE	8
35	12345689	UCO Bank	2026-10-03 15:18:45.929779	SBIN0002489	Gokila	INACTIVE	8
36	12345678	TamilNad Mercantile Bank	2026-10-05 10:49:01.758868	TMBI0002345	Rahul S	ACTIVE	8
37	12345666	HDFC Bank	2026-10-05 15:07:40.429936	HDFC0004567	MadhanKumar	ACTIVE	2
38	12345678	ICICI	2026-10-05 19:32:59.946442	ICIC0002345	Murugaraj	ACTIVE	6
\.


--
-- Data for Name: consents; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.consents (id, created_at, data_access, expires_at, purpose, status, updated_at, customer_id, created_by, approved_at, approved_by, rejected_at, rejected_by) FROM stdin;
34	2026-10-03 10:21:41.013356	TRANSACTIONS	2026-12-31 23:59:59	Transaction History Access	APPROVED	2026-10-03 10:37:53.914357	8	customer1	\N	\N	\N	\N
1	2026-09-30 12:06:36.148896	ACCOUNT	2026-12-31 23:59:59	Account Information Access	APPROVED	2026-09-30 12:18:28.811528	2	legacy	\N	\N	\N	\N
2	2026-09-30 12:07:41.96728	TRANSACTIONS	2026-12-31 23:59:59	Transaction History Access	APPROVED	2026-10-02 22:09:56.934447	3	legacy	\N	\N	\N	\N
35	2026-10-03 18:53:34.646811	BALANCE	2026-12-31 23:59:59	Self Approval Test	REJECTED	2026-10-03 18:56:31.954275	8	admin1	\N	\N	\N	\N
36	2026-10-03 19:07:41.448005	BALANCE	2026-12-31 23:59:59	Balance Access	APPROVED	2026-10-03 19:11:48.31161	8	maker1	2026-10-03 19:11:48.034934	checker1	\N	\N
37	2026-10-03 19:08:13.757411	TRANSACTION	2026-12-31 23:59:59	Transaction History Access	REJECTED	2026-10-03 19:12:05.004074	8	maker1	\N	\N	2026-10-03 19:12:05.002674	checker1
38	2026-10-03 21:30:18.708814	BALANCE,TRANSACTIONS	\N	Account data access	APPROVED	2026-10-03 21:35:05.121931	8	maker1	2026-10-03 21:35:05.113385	checker1	\N	\N
39	2026-10-04 21:04:08.414572	BALANCE,TRANSACTIONS	\N	Account data access	APPROVED	2026-10-04 21:06:30.499724	8	maker1	2026-10-04 21:06:30.492826	checker1	\N	\N
40	2026-10-05 16:40:58.594181	ACCOUNT_DETAILS	2026-11-11 05:40:00	Account information	REJECTED	2026-10-05 19:07:16.503585	39	geetha	\N	\N	2026-10-05 19:07:16.475019	checker1
\.


--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers (id, created_at, email, name, phone, username, password) FROM stdin;
3	2026-09-28 22:03:34.868209	sahana@example.com	Sahana	9486553772	\N	\N
4	2026-09-28 22:03:58.600391	rahul@example.com	Rahul	8072562982	\N	\N
5	2026-09-28 22:04:28.39495	athina@example.com	Athina	9344159535	\N	\N
6	2026-09-28 22:07:54.875396	madhan@example.com	Madhan	9677068776	\N	\N
7	2026-09-29 19:53:54.422509	madhankumar@example.com	Sankar	9677068	\N	\N
2	2026-09-28 22:03:15.379071	gokilaexample.com	Gokila	9344682707	\N	\N
8	2026-09-29 22:35:13.30761	madhankumar@example	Sankar	9677068776	customer1	\N
35	2026-10-05 14:20:54.947607	autocustomer1@example.com	Auto Customer	9876543210	autocustomer2	\N
37	2026-10-05 15:28:18.162284	indhra@example.com	Indhra	9486553772	indhra	\N
39	2026-10-05 15:56:05.659717	geetha@example.com	Geetha	9344682707	Geetha	Geetha123
40	2026-10-05 19:37:03.921373	tgokila459@gmail.com	Gokila	9344682707	Gokila	Gokila22005
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transactions (id, amount, balance_after, description, transaction_date, type, account_id) FROM stdin;
1	5000.00	5000.00	Initial deposit	2026-09-29 09:43:26.9911	DEPOSIT	3
2	2000.00	3000.00	Initial deposit	2026-09-29 09:45:46.817413	WITHDRAWAL	3
34	5000.00	8000.00	Initial deposit	2026-10-03 14:35:28.273975	DEPOSIT	3
35	15000.00	15000.00	Initial deposit	2026-10-03 14:43:22.036457	DEPOSIT	1
36	500.00	14500.00	Initial withdraw	2026-10-03 14:43:56.117947	WITHDRAWAL	1
\.


--
-- Name: accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_id_seq', 37, true);


--
-- Name: beneficiaries_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.beneficiaries_id_seq', 38, true);


--
-- Name: consents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.consents_id_seq', 40, true);


--
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_id_seq', 40, true);


--
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transactions_id_seq', 36, true);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: beneficiaries beneficiaries_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.beneficiaries
    ADD CONSTRAINT beneficiaries_pkey PRIMARY KEY (id);


--
-- Name: consents consents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consents
    ADD CONSTRAINT consents_pkey PRIMARY KEY (id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: accounts uk6kplolsdtr3slnvx97xsy2kc8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk6kplolsdtr3slnvx97xsy2kc8 UNIQUE (account_number);


--
-- Name: customers ukbepynu3b6l8k2ppuq6b33xfxc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT ukbepynu3b6l8k2ppuq6b33xfxc UNIQUE (username);


--
-- Name: customers ukrfbvkrffamfql7cjmen8v976v; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT ukrfbvkrffamfql7cjmen8v976v UNIQUE (email);


--
-- Name: transactions fk20w7wsg13u9srbq3bd7chfxdh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk20w7wsg13u9srbq3bd7chfxdh FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: consents fk5pdjx2imb5xwfjmsh2d6qeucu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consents
    ADD CONSTRAINT fk5pdjx2imb5xwfjmsh2d6qeucu FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: beneficiaries fkmm45xj9n6sed6pswp1iotl8dq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.beneficiaries
    ADD CONSTRAINT fkmm45xj9n6sed6pswp1iotl8dq FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: accounts fkn6x8pdp50os8bq5rbb792upse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fkn6x8pdp50os8bq5rbb792upse FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- PostgreSQL database dump complete
--

\unrestrict FSrh1Xm04TDalytaJLEZ8CoeLnWofr5Pw0y7YTVBRfDZZzzK9idtaTbsUnEKHqL

