spring.application.name=openbank

spring.datasource.url=jdbc:postgresql://localhost:5433/openbank
spring.datasource.username=postgres
spring.datasource.password=Gokila@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/openbank
keycloak.admin.server-url=${KEYCLOAK_ADMIN_SERVER_URL:http://keycloak:8080}
keycloak.admin.realm=master
keycloak.admin.client-id=openbank-backend-admin
keycloak.admin.client-secret=MQxRRQaxs6XgL7cScoxzXmth9Nb27g8bH3VTcWMiRJlcu2FAqE0SJ0BCviYhVeDwsey0rrmzksTARPLcTa4gXj
keycloak.target.realm=openbank

