spring.application.name=openbank

spring.datasource.url=jdbc:postgresql://localhost:5433/openbank
spring.datasource.username=postgres
spring.datasource.password=Gokila@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/openbank